name: 'PR Comment Trigger'
description: 'Trigger match on pull request comment'
author: 'yuler<is.yuler@gmail.com>'
inputs:
  trigger: # change this
    required: true
    description: 'The string match starts with it in pull request comment. For example "/trigger"'
runs:
  using: 'node12'
  main: 'dist/index.js'
