name: 'Test'

on:
  issue_comment:
    types: [created]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: ./
        id: 'pr'
        with:
          trigger: '/trigger'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      # Automatic cancel workflow when mismatch trigger
      - name: Echo
        run: |
          echo Trigger
